"""v7

Revision ID: 3089c32702ca
Revises: dc53c33aeaf9
Create Date: 2024-06-06 16:20:32.606153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3089c32702ca'
down_revision: Union[str, None] = 'dc53c33aeaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Competition', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Competition', 'User', ['userid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Competition', type_='foreignkey')
    op.drop_column('Competition', 'userid')
    # ### end Alembic commands ###
