"""v5

Revision ID: 5a59883b8334
Revises: c3fd9579112b
Create Date: 2024-06-05 19:02:05.353392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a59883b8334'
down_revision: Union[str, None] = 'c3fd9579112b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'user_type',
               existing_type=postgresql.ENUM('ADMIN', 'STUDENT', 'TEACHER', name='usertype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'STUDENT', 'TEACHER', name='usertype'),
               existing_nullable=False)
    # ### end Alembic commands ###
