"""v3

Revision ID: c3fd9579112b
Revises: 82b9cf2ac947
Create Date: 2024-06-05 18:35:40.420848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3fd9579112b"
down_revision: Union[str, None] = "82b9cf2ac947"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("firstname", sa.String(), nullable=True))
    op.add_column("User", sa.Column("lastname", sa.String(), nullable=True))
    op.add_column("User", sa.Column("username", sa.String(), nullable=True))
    op.add_column("User", sa.Column("birthdate", sa.Date(), nullable=True))
    op.drop_column("User", "user_type")
    op.add_column(
        "User",
        sa.Column(
            "user_type",
            sa.Enum("ADMIN", "STUDENT", "TEACHER", name="usertype"),
            nullable=False,
        ),
    )

    op.alter_column(
        "User",
        "user_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("ADMIN", "STUDENT", "TEACHER", name="usertype"),
        existing_nullable=False,
        postgresql_using="user_type::text::usertype",
    )

    op.drop_constraint("User_user_name_key", "User", type_="unique")
    op.create_unique_constraint(None, "User", ["username"])
    op.drop_column("User", "user_name")
    op.drop_column("User", "first_name")
    op.drop_column("User", "last_name")
    op.drop_column("User", "brithdate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("brithdate", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "User", sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "User",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "User", sa.Column("user_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "User", type_="unique")
    op.create_unique_constraint("User_user_name_key", "User", ["user_name"])
    op.alter_column(
        "User",
        "user_type",
        existing_type=sa.Enum("ADMIN", "STUDENT", "TEACHER", name="usertype"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("User", "birthdate")
    op.drop_column("User", "username")
    op.drop_column("User", "lastname")
    op.drop_column("User", "firstname")
    # ### end Alembic commands ###
